import re
from pathlib import Path

#We can't create windows file named with special characters so we filter by regex
_INVALID_CHARS = re.compile(r'[<>:"/\\|?*]')
#The list of characters forbidden have been given by Claude 3.7 Sonnet and verified

#This sanitizing function except docstring have been generated by Claude 3.7 Sonnet and verified
def _sanitize_folder_name(name: str, max_length: int = 200) -> str:
    """ 
    Clearing name to avoid special character and limit the length of the name
    :param name: The name of the assignment.
    :param max_length: The maximum length of the name.
    :return: The sanitized name.
    """
    cleaned = _INVALID_CHARS.sub("_", name).strip()
    return cleaned[:max_length] or "sans_nom"


def create_deposit_folders(assignments: list[dict]) -> None:
    """
    Create the deposit folders for the assignments.

    :param assignments: List of dicts with keys: url, title, due_date_label, due_timestamp, course.
    :return: None
    """
    #If not exists creating the deposit dir
    project_dir = Path(__file__).resolve().parent
    deposit_dir = project_dir / "deposit"

    if not deposit_dir.exists():
        deposit_dir.mkdir(parents=True, exist_ok=True)

    #creating the assignements folders
    for assignment in assignments:
        folder_name = _sanitize_folder_name(assignment["title"])
        folder_path = deposit_dir / folder_name
        folder_path.mkdir(parents=True, exist_ok=True)
