from playwright.sync_api import sync_playwright, Page


def print_dom(page: Page) -> None:
    """
    Retrieves all DOM elements from the current page and prints them (tag, id, class, text).
    Intended for development and debugging only.

    :param page: The page (playwright object) to print the DOM of.
    :return: None
    """
    #Executing JS code to retrieve all DOM elements in the elements variable
    #This JS code has been generated by Claude 3.7 Sonnet and verified
    elements = page.evaluate("""
        () => Array.from(document.querySelectorAll('*')).map(el => ({
            tag: el.tagName.toLowerCase(),
            id: el.id || '',
            class: (el.className && typeof el.className === 'string') ? el.className.trim().slice(0, 50) : '',
            text: (el.innerText || '').trim().slice(0, 60)
        }))
    """)
    # Printing elements in a readable format (index, tag, id, class, text)
    for i, el in enumerate(elements):
        id_part = f" id={el['id']}" if el["id"] else ""
        class_part = f" class={el['class']}" if el["class"] else ""
        text_part = f" → {el['text']}" if el["text"] else ""
        print(f"{i+1:4}. <{el['tag']}{id_part}{class_part}>{text_part}")

